apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility-service-deployment
  labels:
    app: eligibility-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eligibility-service
  template:
    metadata:
      labels:
        app: eligibility-service
        monitor: "true"
    spec:
      containers:
        - name: eligibility
          image: fluescher/sustaino-dummy-service
          ports:
            - name: web
              containerPort: 9000

---
kind: Service
apiVersion: v1
metadata:
  name: eligibility-service
spec:
  selector:
    app: eligibility-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
