apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eligibility-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitor: "true"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: web
      path: /metrics
